global using OneOf;
global using OAuth.DrawApp.Errors;
global using OAuth.DrawApp.Markers;
global using OAuth.DrawApp.Database;
global using OAuth.DrawApp.Extensions;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Swashbuckle.AspNetCore.Filters;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;