global using OneOf;
global using OAuth.Draw.Errors;
global using OAuth.Draw.Markers;
global using OAuth.Draw.Database;
global using OAuth.Draw.Extensions;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Swashbuckle.AspNetCore.Filters;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;